server:
  port: 18082
spring:
  application:
    name: discovery-provider
  zipkin:
    base-url: http://10.23.191.242:5005 #代表字zipkin服务器地址
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0 #0.1-1.0 也就是代表链路跟踪的数据上传的概率有多大  
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8090
feign:
  sentinel:
    enabled: true


    